  swagger: "2.0"
  info: 
    version: "1.0.0"
    title: "Swagger for simple w3Schools"
    description: "A sample APIs that post new languages , lessons and examples"
  host: "petstore.swagger.io"
  basePath: "/api"
  schemes: 
    - "http"
  consumes: 
    - "application/json"
  produces: 
    - "application/json"
  paths: 
  /movies:
    get:
      description: Returns all languages
      parameters:
